services:
  - type: web
    name: creditclear-backend
    env: python
    buildCommand: pip install -r render-requirements.txt
    startCommand: gunicorn simple_start:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --workers 4
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: LOG_LEVEL
        value: info
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
